export enum BookAudience {
	CHILDREN = 'CHILDREN',
	TEEN = 'TEEN',
	GENERAL = 'GENERAL',
	UNDERGRADUATE = 'UNDERGRADUATE',
	GRADUATE = 'GRADUATE',
	PROFESSIONAL = 'PROFESSIONAL',
}

export enum BookFormat {
	PAPERBACK = 'PAPERBACK',
	EBOOK = 'EBOOK',
	AUDIOBOOK = 'AUDIOBOOK',
}

export enum BookType {
	TEXTBOOK = 'TEXTBOOK',
	REFERENCE = 'REFERENCE',
	RESEARCH = 'RESEARCH',
	NOVEL = 'NOVEL',
	COMIC = 'COMIC',
	MAGAZINE = 'MAGAZINE',
	JOURNAL = 'JOURNAL',
	WORKBOOK = 'WORKBOOK',
	MANUAL = 'MANUAL',
	DICTIONARY = 'DICTIONARY',
	ENCYCLOPEDIA = 'ENCYCLOPEDIA',
	OTHER = 'OTHER',
}

export enum BookCategory {
	ROMANCE = 'ROMANCE',
	SCIENCE_FICTION = 'SCIENCE_FICTION',
	MYSTERY_THRILLER = 'MYSTERY_THRILLER',
	SELF_IMPROVEMENT = 'SELF_IMPROVEMENT',
	CHILDRENS_BOOKS = 'CHILDRENS_BOOKS',
	COMICS = 'COMICS',
	LITERATURE = 'LITERATURE',
	ARTS_AND_PHOTOGRAPHY = 'ARTS_AND_PHOTOGRAPHY',
	COOKBOOKS = 'COOKBOOKS',
	HEALTH_FITNESS = 'HEALTH_FITNESS',
	HUMOR_ENTERTAINMENT = 'HUMOR_ENTERTAINMENT',
	MEDICAL_BOOKS = 'MEDICAL_BOOKS',
	POLITICS_AND_SOCIAL_SCIENCES = 'POLITICS_AND_SOCIAL_SCIENCES',
	SCIENCE_AND_MATH = 'SCIENCE_AND_MATH',
	SPORTS_AND_OUTDOORS = 'SPORTS_AND_OUTDOORS',
	TEST_PREPARATION = 'TEST_PREPARATION',
	TRAVEL = 'TRAVEL',
	TEXTBOOKS = 'TEXTBOOKS',
	MAGAZINES = 'MAGAZINES',
	LAW = 'LAW',
	COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
	ENGINEERING = 'ENGINEERING',
	BUSINESS = 'BUSINESS',
	DESIGN = 'DESIGN',
	KOREAN_LANGUAGE = 'KOREAN_LANGUAGE',
	TOPIK_PREPARATION = 'TOPIK_PREPARATION',

	OTHER = 'OTHER',
}

export enum BookLanguage {
	ENGLISH = 'ENGLISH',
	KOREAN = 'KOREAN',
	CHINESE = 'CHINESE',
	SPANISH = 'SPANISH',
	FRENCH = 'FRENCH',
	GERMAN = 'GERMAN',
	RUSSIAN = 'RUSSIAN',
	ARABIC = 'ARABIC',
	UZBEK = 'UZBEK',
	OTHER = 'OTHER',
}

export enum BookStatus {
	// Temporary compatibility for existing request flow.
	AVAILABLE = 'AVAILABLE',
	RESERVED = 'RESERVED',

	ACTIVE = 'ACTIVE',
	HIDDEN = 'HIDDEN',
	SOLD = 'SOLD',
	DELETED = 'DELETED',
}
