export enum LibraryBookAudience {
	CHILDREN = 'CHILDREN',
	TEEN = 'TEEN',
	GENERAL = 'GENERAL',
	UNDERGRADUATE = 'UNDERGRADUATE',
	GRADUATE = 'GRADUATE',
	PROFESSIONAL = 'PROFESSIONAL',
}

export enum LibraryBookFormat {
	PAPERBACK = 'PAPERBACK',
	EBOOK = 'EBOOK',
	AUDIOBOOK = 'AUDIOBOOK',
}

export enum LibraryBookType {
	TEXTBOOK = 'TEXTBOOK',
	REFERENCE = 'REFERENCE',
	RESEARCH = 'RESEARCH',
	NOVEL = 'NOVEL',
	COMIC = 'COMIC',
	MAGAZINE = 'MAGAZINE',
	JOURNAL = 'JOURNAL',
	WORKBOOK = 'WORKBOOK',
	MANUAL = 'MANUAL',
	DICTIONARY = 'DICTIONARY',
	ENCYCLOPEDIA = 'ENCYCLOPEDIA',
	OTHER = 'OTHER',
}

export enum LibraryBookCategory {
	ROMANCE = 'ROMANCE',
	SCIENCE_FICTION = 'SCIENCE_FICTION',
	MYSTERY_THRILLER = 'MYSTERY_THRILLER',
	SELF_IMPROVEMENT = 'SELF_IMPROVEMENT',
	CHILDRENS_BOOKS = 'CHILDRENS_BOOKS',
	COMICS = 'COMICS',
	LITERATURE = 'LITERATURE',
	ARTS_AND_PHOTOGRAPHY = 'ARTS_AND_PHOTOGRAPHY',
	COOKBOOKS = 'COOKBOOKS',
	HEALTH_FITNESS = 'HEALTH_FITNESS',
	HUMOR_ENTERTAINMENT = 'HUMOR_ENTERTAINMENT',
	MEDICAL_BOOKS = 'MEDICAL_BOOKS',
	POLITICS_AND_SOCIAL_SCIENCES = 'POLITICS_AND_SOCIAL_SCIENCES',
	SCIENCE_AND_MATH = 'SCIENCE_AND_MATH',
	SPORTS_AND_OUTDOORS = 'SPORTS_AND_OUTDOORS',
	TEST_PREPARATION = 'TEST_PREPARATION',
	TRAVEL = 'TRAVEL',
	TEXTBOOKS = 'TEXTBOOKS',
	MAGAZINES = 'MAGAZINES',
	LAW = 'LAW',
	COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
	ENGINEERING = 'ENGINEERING',
	BUSINESS = 'BUSINESS',
	DESIGN = 'DESIGN',
	KOREAN_LANGUAGE = 'KOREAN_LANGUAGE',
	TOPIK_PREPARATION = 'TOPIK_PREPARATION',
	OTHER = 'OTHER',
}

export enum LibraryBookLanguage {
	ENGLISH = 'ENGLISH',
	KOREAN = 'KOREAN',
	CHINESE = 'CHINESE',
	SPANISH = 'SPANISH',
	FRENCH = 'FRENCH',
	GERMAN = 'GERMAN',
	RUSSIAN = 'RUSSIAN',
	ARABIC = 'ARABIC',
	UZBEK = 'UZBEK',
	OTHER = 'OTHER',
}

export enum LibraryBookStatus {
	AVAILABLE = 'AVAILABLE',
	RESERVED = 'RESERVED',
	ACTIVE = 'ACTIVE',
	HIDDEN = 'HIDDEN',
	SOLD = 'SOLD',
	DELETED = 'DELETED',
}

export enum LibraryBookInventoryType {
	LIBRARY = 'LIBRARY',
	COMMERCIAL = 'COMMERCIAL',
}

export enum LibraryBookStorageZone {
	LIBRARY_SHELF = 'LIBRARY_SHELF',
	COMMERCIAL_WAREHOUSE = 'COMMERCIAL_WAREHOUSE',
}

export enum LibraryBookInventoryStatus {
	AVAILABLE = 'AVAILABLE',
	RESERVED = 'RESERVED',
	BORROWED = 'BORROWED',
	IN_DELIVERY = 'IN_DELIVERY',
	MISSING = 'MISSING',
}

export enum LibraryRobotStatus {
	OFFLINE = 'OFFLINE',
	IDLE = 'IDLE',
	ASSIGNED = 'ASSIGNED',
	NAVIGATING = 'NAVIGATING',
	VERIFYING_BOOK = 'VERIFYING_BOOK',
	PICKING_UP = 'PICKING_UP',
	DELIVERING = 'DELIVERING',
	RETURNING = 'RETURNING',
	DOCKING = 'DOCKING',
	ERROR = 'ERROR',
	MAINTENANCE = 'MAINTENANCE',
}

export enum LibraryRequestType {
	BORROW = 'BORROW',
	PURCHASE = 'PURCHASE',
}

export enum LibraryDeliveryDestinationType {
	STUDENT_DESK = 'STUDENT_DESK',
	RECEPTION = 'RECEPTION',
}

export enum LibraryPaymentStatus {
	NOT_REQUIRED = 'NOT_REQUIRED',
	PAY_AT_RECEPTION = 'PAY_AT_RECEPTION',
	PAID = 'PAID',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
}

export enum LibraryRequestStatus {
	QUEUED = 'QUEUED',
	ASSIGNED = 'ASSIGNED',
	DISPATCHED = 'DISPATCHED',
	NAVIGATING_TO_SHELF = 'NAVIGATING_TO_SHELF',
	ARRIVED_AT_SHELF = 'ARRIVED_AT_SHELF',
	VERIFYING_BOOK = 'VERIFYING_BOOK',
	BOOK_FOUND = 'BOOK_FOUND',
	BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
	PICKING_UP = 'PICKING_UP',
	DELIVERING = 'DELIVERING',
	ARRIVED_AT_STUDENT = 'ARRIVED_AT_STUDENT',
	READY = 'READY',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum LibraryRequestErrorCode {
	BOOK_UNAVAILABLE = 'BOOK_UNAVAILABLE',
	NO_ROBOT_AVAILABLE = 'NO_ROBOT_AVAILABLE',
	INVALID_DESTINATION = 'INVALID_DESTINATION',
	ROBOT_OFFLINE = 'ROBOT_OFFLINE',
	NAVIGATION_FAILED = 'NAVIGATION_FAILED',
	PICKUP_FAILED = 'PICKUP_FAILED',
	BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
	USER_CANCELLED = 'USER_CANCELLED',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export enum LibraryMemberType {
	USER = 'USER',
	ADMIN = 'ADMIN',
}

export enum LibraryMemberStatus {
	ACTIVE = 'ACTIVE',
	BLOCK = 'BLOCK',
	DELETE = 'DELETE',
}

export enum LibraryMemberAuthType {
	PHONE = 'PHONE',
	EMAIL = 'EMAIL',
	TELEGRAM = 'TELEGRAM',
}

// Backend currently exposes pickupDirection as a string field, with FRONT used by default.
export enum LibraryPickupDirection {
	FRONT = 'FRONT',
}

export type PickupDirection = LibraryPickupDirection | string;
