export enum RequestType {
	BORROW = 'BORROW',
	PURCHASE = 'PURCHASE',
}

export enum DeliveryDestinationType {
	STUDENT_DESK = 'STUDENT_DESK',
	RECEPTION = 'RECEPTION',
}

export enum PaymentStatus {
	NOT_REQUIRED = 'NOT_REQUIRED',
	PAY_AT_RECEPTION = 'PAY_AT_RECEPTION',
	PAID = 'PAID',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
}

export enum RequestStatus {
	QUEUED = 'QUEUED',
	ASSIGNED = 'ASSIGNED',
	DISPATCHED = 'DISPATCHED',
	NAVIGATING_TO_SHELF = 'NAVIGATING_TO_SHELF',
	ARRIVED_AT_SHELF = 'ARRIVED_AT_SHELF',
	VERIFYING_BOOK = 'VERIFYING_BOOK',
	BOOK_FOUND = 'BOOK_FOUND',
	BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
	PICKING_UP = 'PICKING_UP',
	DELIVERING = 'DELIVERING',
	ARRIVED_AT_STUDENT = 'ARRIVED_AT_STUDENT',
	READY = 'READY',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum RequestErrorCode {
	BOOK_UNAVAILABLE = 'BOOK_UNAVAILABLE',
	NO_ROBOT_AVAILABLE = 'NO_ROBOT_AVAILABLE',
	INVALID_DESTINATION = 'INVALID_DESTINATION',
	ROBOT_OFFLINE = 'ROBOT_OFFLINE',
	NAVIGATION_FAILED = 'NAVIGATION_FAILED',
	PICKUP_FAILED = 'PICKUP_FAILED',
	BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
	USER_CANCELLED = 'USER_CANCELLED',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
}
